# Common / default settings
greeting.message=Hello from Quarkus
app.environment=local
quarkus.http.port=8080

# Container image settings
# IMPORTANT: Replace YOUR_DOCKERHUB_USERNAME with your real Docker Hub username
quarkus.container-image.group=bhanurajeev
quarkus.container-image.name=quarkus-devops-demo
quarkus.container-image.tag=dev-local
quarkus.container-image.build=true